### ISSUE TITLE
Does not record user/password

### ISSUE THREAD

**Issue by erdanieee** [caseyscarborough/keylogger#12] opened 2016-07-13 08:17 UTC
The keylogger works correctly except for user/password. For example, if you use Safari/firefox to log in your email account, the user/password is not recorded. The same for keychain password and other programs...

**Comment by ghostlymedic** [comment] 2016-07-15 00:51
Same issue, then I found the answer/reason it's not possible in a closed issue. Reference [Issue #3](https://github.com/caseyscarborough/keylogger/issues/3)

**Comment by caseyscarborough** [comment] 2016-07-15 20:48
Duplicate of #3.

**Closed by caseyscarborough** 2016-07-15 20:48 UTC
