### ISSUE TITLE
Modifiers are logged twice

### ISSUE THREAD

**Issue by forthrin** [caseyscarborough/keylogger#9] opened 2016-05-27 06:42 UTC
All modifiers (shift, fn, ctrl, alt, cmd) are logged both on key down and key up, causing duplicate entries in the log file.

Other keys which are logged on key down only.

Suggest to log key down only for all keys.

**Comment by caseyscarborough** [comment] 2016-05-27 09:52
Closing this, as it's a duplicate of #8.

**Closed by caseyscarborough** 2016-05-27 09:52 UTC
